name: rx_change_3
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^3.0.1
  
 

  ## -- SLIDER   
  flutter_carousel_slider: ^1.0.8
  carousel_slider: ^4.0.0
  provider: ^6.0.4


  ## -- AUTHENTIFICATION LOCAL
  local_auth: ^2.1.2


  flutter_lints: ^2.0.0
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^2.1.1
  flutter_svg: ^1.1.6

  http: ^0.13.4
  shared_preferences: ^2.0.11
  web3dart: ^2.3.5
  web_socket_channel: ^2.1.0
  cupertino_icons: ^1.0.2
  syncfusion_flutter_sliders: ^20.3.56

  # -- ONBOARDING SCREEN
  get: ^4.6.5
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2

  # -- FIREBASE PACKAGE
  firebase_auth: ^4.1.1
  firebase_core: ^2.2.0
  cloud_firestore: ^4.0.5
 

  ## -- ICON PACKAGES
  line_awesome_flutter: ^2.0.0
  animated_theme_switcher: ^2.0.7






  # dio: ^4.0.4
  # intl: ^0.16.1
  

  # flutter_signin_button: ^2.0.0
  # firebase_dynamic_links: ^5.0.4
  # sqflite: any
  # path: any
  # font_awesome_flutter: ^8.10.0
  # API plugin
  # telephony:
  # country_pickers: ^1.3.0 pour appeler les drapeaus des pays
  # advanced_ussd:
  # flutter_background_service:
  # alarm_service:
  # intl_phone_field: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# -- FLUTTER NATIVE SPLASH SCREEN
  flutter_native_splash: ^2.2.14

flutter_native_splash:
  color: "#358C0D"
  color_dark: "#F1C213"
  branding: assets/images/background.png
  image: assets/images/rxchange_2blanc.png
  image_dark: assets/images/rxchange_2blanc.png

android_12:
  image: assets/images/rxchange_2blanc.png
  icon_backgroun_color: "#F1C213"
  image_dark: assets/images/rxchange_2blanc.png
  icon_backgroun_color_dark: "#358C0D"


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding/
    - src/artifacts/
    - .env


  fonts:
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          style: italic
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
   